### ISSUE TITLE
content appended bellow editor

### ISSUE THREAD

**Issue by cahyowhy** [froala/ember-froala-editor#57] opened 2018-03-27 03:51 UTC
something strange here.. the content is apended both on editor and below editor...
![image](https://user-images.githubusercontent.com/18083469/37945896-c01f1f16-31ac-11e8-8591-5c787eb01606.png)

**Comment by Panman8201** [comment] 2018-03-27 12:44
I have not seen this before. Are you sure the property isn't being output just below the editor too? What plugins are you using and what are your options for the editor? I can try replicating.

**Comment by Panman8201** [comment] 2018-04-04 12:59
Get any farther on this @cahyowhy ? If you're still having issues, post your editor options and which plugins you're importing. Thx

**Comment by cahyowhy** [comment] 2018-04-14 04:07
Iam use ember-froala-editor btw, iam use that lib on in repo plugin.

**Comment by Panman8201** [comment] 2018-04-16 17:58
Alright, sounds like you're using it in an in-repo addon. Are you able to provide your configuration options?

By the looks of it, there is something else going on as well, because the character count in your screenshot is below the editor too. My first thought is something elsewhere is changing the styling for the editor DOM elements. Perhaps some inspection on the elements at the bottom will clue you into the root problem.

**Comment by Panman8201** [comment] 2018-05-09 15:53
Were you ever able to figure out the problem here? Still think it's a styling thing as I'm not able to replicate the issue.

**Comment by cahyowhy** [comment] 2018-05-19 11:09
hmm i forgot the project is still on my ext hd hehe, maybe tomorrow i'll upload  to git

**Comment by Panman8201** [comment] 2018-05-29 13:05
I wonder if this is what you're running into: https://github.com/emberjs/ember.js/issues/14924

Because this addon does use triple curlies because it's not known if the passed in string is SafeString or not. https://github.com/froala/ember-froala-editor/blob/v2.8.1/addon/templates/components/froala-editor.hbs#L3

**Comment by viniciussbs** [comment] 2018-06-01 19:15
Same here:

![image](https://user-images.githubusercontent.com/245791/40859086-f1063e0a-65b6-11e8-9df1-2710ec73db6e.png)

**Comment by Panman8201** [comment] 2018-06-01 21:29
@viniciussbs @cahyowhy I pushed changes to master which might fix this (in relation to the ember bug I linked to earlier). Try installing from master to see if the issue goes away, let me know. Thanks

```
npm install froala/ember-froala-editor#master --save-dev
```

**Comment by Panman8201** [comment] 2018-06-08 16:54
Ok, I have a fastboot example spun-up to test with but still cannot replicate. Can you describe your route structure and where the editor is placed? For example, is there a sub-route from where the editor is placed? Any other details that you feel would be important would greatly help. Thanks!

**Comment by viniciussbs** [comment] 2018-06-08 22:35
@Panman8201 is this block supposed to run only when the app **is running on FastBoot**? Or when the app **has the `service:fastboot`**, even when its running on the browser?

https://github.com/froala/ember-froala-editor/blob/master/addon/components/froala-editor.js#L191-L195

@raphaelns-developer works with me and we use this addon in two different apps. One uses `ember-cli-fastboot` and is the one where we found this issue. The other app does not use `ember-cli-fastboot` and works fine. He noticed that the block that I mentioned is always executed in the app that has `ember-cli-fastboot` installed, even when the app is running on the browser. Changing the `if` condition to `this.get('fastboot') && this.get('fastboot.isFastBoot')` solved the problem. Maybe only `this.get('fastboot.isFastBoot')` will work, but we haven't tried it.

This also solves another issue we are facing: `Failed to execute 'removeChild' on 'node': the node to be removed is not a child of this node`.

![image](https://user-images.githubusercontent.com/245791/41183761-b58d007e-6b52-11e8-8c01-40478be91667.png)

It happens when the editor already has some content and you try to update it. Both situations ware solved changing the `if` condition to check if the is running on FastBoot.

**Comment by Panman8201** [comment] 2018-06-11 16:27
> @Panman8201 is this block supposed to run only when the app is running on FastBoot? Or when the app has the service:fastboot, even when its running on the browser?

Yes, there are several scenarios for updating the content based on state. In that case, that block is only for Fastboot.

> Changing the if condition to this.get('fastboot') && this.get('fastboot.isFastBoot') solved the problem. Maybe only this.get('fastboot.isFastBoot') will work, but we haven't tried it.

Humm... I was told that just checking for the service would be enough but apparently not... Care to submit a PR? Or else I can certainly make the change too.

> This also solves another issue we are facing: Failed to execute 'removeChild' on 'node': the node to be removed is not a child of this node.

That is exactly the reason for this: https://github.com/froala/ember-froala-editor/blob/v2.8.1/addon/components/froala-editor.js#L198-L202 Do you know the state which you're in when the error occurs?

**Comment by viniciussbs** [comment] 2018-06-11 20:07
> That is exactly the reason for this: https://github.com/froala/ember-froala-editor/blob/v2.8.1/addon/components/froala-editor.js#L198-L202 Do you know the state which you're in when the error occurs?

@Panman8201 According to @raphaelns-developer's tests, every case was reaching the first `if` block, because it always evaluates `true` when the app has `ember-cli-fastboot` as a dependency. So we never reach this `else if` block that you mentioned. I can double check it if you want.

> Humm... I was told that just checking for the service would be enough but apparently not... 

I guess checking for the service is a safe way to know if you can use the service without breaking apps that don't use FastBoot, but not to check if the app is running on FastBoot.

> Care to submit a PR? Or else I can certainly make the change too.

@raphaelns-developer will submit a PR later today.

**Comment by raphaelns-developer** [comment] 2018-06-11 22:05
#63 @Panman8201 I submited a PR with two corrections:
- The `if` block at `didUpdateAttrs` 
- The `if` block at `included` function of the `index.js` file

**Comment by Panman8201** [comment] 2018-06-12 21:21
Thanks @raphaelns-developer and @viniciussbs !! Merged the PR. We're on the froala-editor release train so it'll come out the next time they release a new version. Or else you can checkout from master if you'd like, but it sounds like you already confirmed the fix on your own. Just to confirm, this also fixes the double render content issue this case was originally started for??

**Comment by raphaelns-developer** [comment] 2018-06-13 10:51
Yes @Panman8201 . The double render content issue was fixed with this update.

**Comment by Panman8201** [comment] 2018-07-17 15:47
Finally published a new version, this fix is in 2.8.4. Thanks everyone!

**Closed by Panman8201** 2018-07-17 15:47 UTC
Labels: investigating
