### ISSUE TITLE
Disappear when content is changed to null or false

### ISSUE THREAD

**Issue by niksa88** [froala/ember-froala-editor#40] opened 2017-06-26 13:22 UTC
`{{froala-editor content=object.description update=(action (mut object.description)) on-blur=(froala-method "reinit") options=(hash initOnClick=true)}}`

When I manually change content to null or false the editor disappear. 

Change

`this.set('object.description', false)`

init value is null and its working but after change editor disappear without error.

**Comment by Panman8201** [comment] 2017-06-26 17:02
Interesting, will investigate..

**Comment by Panman8201** [comment] 2017-06-26 19:22
[This is the cause](https://github.com/froala/ember-froala-editor/blob/v2.6.2/addon/components/froala-editor.js#L232-L236), because the ember component `{{froala-editor}}` doesn't have access to the `editor` right away when the `initOnClick` option is used, it overwrites the editors html.

@stefanneculai Is there an internal initialization hook that we can tie into? The [ember integration](https://github.com/froala/ember-froala-editor/blob/v2.6.2/addon/components/froala-editor.js#L289-L292) does some [initial setup](https://github.com/froala/ember-froala-editor/blob/v2.6.2/addon/components/froala-editor.js#L347-L454) on the editors [`initialized` hook](https://www.froala.com/wysiwyg-editor/docs/events#initialized). However, when the [`initOnClick` option](https://www.froala.com/wysiwyg-editor/docs/options#initOnClick) is used, that hook is not fired right away. I'm hopeful there is some way we can run code right after `$('.editor').froalaEditor()` no mater what, even if `initOnClick` is used.

**Comment by Panman8201** [comment] 2017-07-20 13:44
FYI, there is a solution for this bug coming in the next version of froala-editor. I'll make the proper adjustments to this addon after that before releasing a new version here.

**Comment by stefanneculai** [comment] 2017-07-20 14:15
@Panman8201 we just made the release for V2.6.3. The new event should be available now there. Thanks!

**Comment by Panman8201** [comment] 2017-07-20 16:43
@stefanneculai Alright, thanks for the heads up. I'll take care of this tonight along with one other thing to be merged. After that I'll release 2.6.3 of this addon.

**Closed** 2017-07-21 02:06 UTC
Labels: bug
